// src/api/mockApi.js

// This combines all provided data snippets into a single, comprehensive array.
export const allData = [
  {
    "id": 1,
    "serviceName": "TechnoSoft IT Solutions",
    "category": "Consulting",
    "description": "Provides IT consulting, digital transformation, and enterprise software implementation for medium and large businesses across India.",
    "averagePricing": "₹50,000 - ₹5,00,000",
    "rating": 4.6,
    "reviewsCount": 340,
    "location": "Bengaluru, Karnataka",
    "availability": "Both",
    "contact": {"email": "info@technosoft.in", "phone": "+91 98450 12345"},
    "website": "https://www.technosoft.in",
    "imageUrl": "https://dummyimage.com/600x400/0044ff/ffffff&text=TechnoSoft",
    "foundedYear": 2010,
    "clientsServed": 1200,
    "languagesSupported": ["English", "Hindi", "Kannada"],
    "featuredServices": ["Cloud Migration", "ERP Consulting", "Custom Software Development"]
  },
  {
    "id": 2,
    "serviceName": "MediCare Health Services",
    "category": "Service",
    "description": "Offers doorstep health checkups, doctor consultations, pathology tests, and wellness programs across Tier 1 and Tier 2 Indian cities.",
    "averagePricing": "₹500 - ₹15,000",
    "rating": 4.4,
    "reviewsCount": 210,
    "location": "Mumbai, Maharashtra",
    "availability": "Offline",
    "contact": {"email": "support@medicareindia.com", "phone": "+91 93210 67890"},
    "website": "https://www.medicareindia.com",
    "imageUrl": "https://dummyimage.com/600x400/ff4444/ffffff&text=MediCare",
    "foundedYear": 2015,
    "clientsServed": 80000,
    "languagesSupported": ["English", "Hindi", "Marathi"],
    "featuredServices": ["Health Checkups", "Doctor on Call", "Pathology Tests", "Corporate Wellness Programs"]
  },
  {
    "id": 3,
    "serviceName": "FinEdge Wealth Consultants",
    "category": "Consulting",
    "description": "Provides financial planning, investment advisory, and tax consultancy for individuals and corporates in India.",
    "averagePricing": "₹10,000 - ₹2,00,000",
    "rating": 4.8,
    "reviewsCount": 420,
    "location": "Delhi NCR",
    "availability": "Both",
    "contact": {"email": "contact@finedge.in", "phone": "+91 98101 44556"},
    "website": "https://www.finedge.in",
    "imageUrl": "https://dummyimage.com/600x400/22cc88/ffffff&text=FinEdge",
    "foundedYear": 2008,
    "clientsServed": 9500,
    "languagesSupported": ["English", "Hindi"],
    "featuredServices": ["Tax Planning", "Investment Advisory", "Retirement Planning", "Corporate Finance Consulting"]
  },
  {
    "id": 4,
    "serviceName": "SkillEdge Training Hub",
    "category": "Service",
    "description": "Offers job-ready skill development courses, IT training, and corporate workshops with certification in multiple domains.",
    "averagePricing": "₹2,000 - ₹75,000",
    "rating": 4.5,
    "reviewsCount": 150,
    "location": "Hyderabad, Telangana",
    "availability": "Online",
    "contact": {"email": "trainings@skilledge.com", "phone": "+91 98765 43210"},
    "website": "https://www.skilledge.com",
    "imageUrl": "https://dummyimage.com/600x400/ffaa00/ffffff&text=SkillEdge",
    "foundedYear": 2017,
    "clientsServed": 40000,
    "languagesSupported": ["English", "Hindi", "Telugu"],
    "featuredServices": ["IT Courses", "Soft Skills Training", "Corporate Workshops", "Placement Assistance"]
  },
  {
    "id": 5,
    "serviceName": "AgriGrow Consultancy",
    "category": "Consulting",
    "description": "Provides expert agricultural consultancy for crop planning, irrigation management, and government scheme guidance.",
    "averagePricing": "₹5,000 - ₹1,00,000",
    "rating": 4.3,
    "reviewsCount": 95,
    "location": "Nagpur, Maharashtra",
    "availability": "Offline",
    "contact": {"email": "help@agrigrow.in", "phone": "+91 90123 45678"},
    "website": "https://www.agrigrow.in",
    "imageUrl": "https://dummyimage.com/600x400/55aa44/ffffff&text=AgriGrow",
    "foundedYear": 2012,
    "clientsServed": 6000,
    "languagesSupported": ["Hindi", "Marathi", "English"],
    "featuredServices": ["Crop Planning", "Organic Farming Consultancy", "Irrigation Guidance", "Soil Testing Support"]
  },
  {
    "id": 6,
    "serviceName": "EduBridge Career Services",
    "category": "Service",
    "description": "Career counseling, student mentoring, admission guidance, and test preparation for Indian and international education.",
    "averagePricing": "₹1,000 - ₹50,000",
    "rating": 4.7,
    "reviewsCount": 280,
    "location": "Pune, Maharashtra",
    "availability": "Both",
    "contact": {"email": "career@edubridge.in", "phone": "+91 96542 78123"},
    "website": "https://www.edubridge.in",
    "imageUrl": "https://dummyimage.com/600x400/6600cc/ffffff&text=EduBridge",
    "foundedYear": 2016,
    "clientsServed": 12000,
    "languagesSupported": ["English", "Hindi", "Marathi"],
    "featuredServices": ["Career Counselling", "Test Preparation", "University Admission Support", "Overseas Education Guidance"]
  },
  {
    "id": 7,
    "serviceName": "HealthFirst Consultancy",
    "category": "Consulting",
    "description": "HealthFirst Consultancy provides expert healthcare advisory services for hospitals, clinics, and startups in India.",
    "averagePricing": "₹1,00,000 - ₹5,00,000",
    "rating": 4.6,
    "reviewsCount": 980,
    "location": "Bengaluru, Karnataka",
    "availability": "Both",
    "contact": {"email": "support@healthfirst.in", "phone": "+91 98450 22345"},
    "website": "https://www.healthfirst.in",
    "imageUrl": "https://dummyimage.com/600x400/ff6347/ffffff&text=HealthFirst",
    "foundedYear": 2012,
    "clientsServed": 500,
    "languagesSupported": ["English", "Hindi", "Kannada"],
    "featuredServices": ["Hospital Infrastructure Consulting", "Healthcare Compliance Advisory", "Digital Health Transformation", "Telemedicine Setup"]
  },
  {
    "id": 8,
    "serviceName": "SkillEdge IT Training",
    "category": "Service",
    "description": "SkillEdge provides corporate IT training programs and upskilling services for professionals across India.",
    "averagePricing": "₹25,000 - ₹1,50,000",
    "rating": 4.8,
    "reviewsCount": 1420,
    "location": "Hyderabad, Telangana",
    "availability": "Both",
    "contact": {"email": "info@skilledge.com", "phone": "+91 97012 33445"},
    "website": "https://www.skilledge.com",
    "imageUrl": "https://dummyimage.com/600x400/1e90ff/ffffff&text=SkillEdge",
    "foundedYear": 2016,
    "clientsServed": 2200,
    "languagesSupported": ["English", "Hindi", "Telugu"],
    "featuredServices": ["Full Stack Development Training", "Cloud & DevOps Workshops", "AI/ML Professional Programs"]
  },
  {
    "id": 9,
    "serviceName": "AgriSmart Solutions",
    "category": "Consulting",
    "description": "AgriSmart Solutions helps farmers adopt modern farming practices through smart irrigation and crop monitoring.",
    "averagePricing": "₹50,000 - ₹3,00,000",
    "rating": 4.5,
    "reviewsCount": 750,
    "location": "Nagpur, Maharashtra",
    "availability": "Offline",
    "contact": {"email": "info@agrismart.in", "phone": "+91 93700 11234"},
    "website": "https://www.agrismart.in",
    "imageUrl": "https://dummyimage.com/600x400/32cd32/ffffff&text=AgriSmart",
    "foundedYear": 2010,
    "clientsServed": 1600,
    "languagesSupported": ["Marathi", "Hindi", "English"],
    "featuredServices": ["Smart Irrigation Systems", "Crop Monitoring Consultancy", "Agri Finance Assistance"]
  },
  {
    "id": 10,
    "serviceName": "FinServe Advisors",
    "category": "Consulting",
    "description": "FinServe Advisors provides financial consultancy for SMEs, specializing in taxation and investment planning.",
    "averagePricing": "₹75,000 - ₹6,00,000",
    "rating": 4.7,
    "reviewsCount": 1120,
    "location": "Mumbai, Maharashtra",
    "availability": "Both",
    "contact": {"email": "contact@finserve.in", "phone": "+91 98200 45678"},
    "website": "https://www.finserve.in",
    "imageUrl": "https://dummyimage.com/600x400/ffd700/000000&text=FinServe",
    "foundedYear": 2008,
    "clientsServed": 2100,
    "languagesSupported": ["English", "Hindi", "Marathi"],
    "featuredServices": ["Taxation & Compliance", "Startup Funding Advisory", "Wealth Management"]
  },
  {
    "id": 11,
    "serviceName": "TravelEase Services",
    "category": "Service",
    "description": "TravelEase offers curated travel and tourism services for domestic and international trips.",
    "averagePricing": "₹20,000 - ₹2,50,000",
    "rating": 4.3,
    "reviewsCount": 1540,
    "location": "Delhi NCR",
    "availability": "Both",
    "contact": {"email": "support@travelease.in", "phone": "+91 98710 66789"},
    "website": "https://www.travelease.in",
    "imageUrl": "https://dummyimage.com/600x400/ff69b4/ffffff&text=TravelEase",
    "foundedYear": 2015,
    "clientsServed": 5200,
    "languagesSupported": ["English", "Hindi"],
    "featuredServices": ["Domestic Holiday Packages", "International Tours", "Corporate Travel Solutions"]
  },
  {
    "id": 12,
    "serviceName": "BuildRight Infra Consultancy",
    "category": "Consulting",
    "description": "BuildRight provides end-to-end consultancy for construction, infrastructure, and real estate projects.",
    "averagePricing": "₹2,00,000 - ₹15,00,000",
    "rating": 4.4,
    "reviewsCount": 890,
    "location": "Ahmedabad, Gujarat",
    "availability": "Offline",
    "contact": {"email": "info@buildright.com", "phone": "+91 98795 44566"},
    "website": "https://www.buildright.com",
    "imageUrl": "https://dummyimage.com/600x400/a0522d/ffffff&text=BuildRight",
    "foundedYear": 2005,
    "clientsServed": 1200,
    "languagesSupported": ["Gujarati", "Hindi", "English"],
    "featuredServices": ["Architectural Planning", "Project Budgeting", "Legal & RERA Compliance"]
  },
  {
    "id": 13,
    "serviceName": "TalentEdge HR Consultancy",
    "category": "Consulting",
    "description": "TalentEdge specializes in HR consulting, including talent acquisition, payroll management, and performance appraisal systems.",
    "averagePricing": "₹40,000 - ₹2,00,000",
    "rating": 4.5,
    "reviewsCount": 540,
    "location": "Pune, Maharashtra",
    "availability": "Both",
    "contact": {"email": "contact@talentedgehr.in", "phone": "+91-9765432109"},
    "website": "https://www.talentedgehr.in",
    "imageUrl": "https://dummyimage.com/600x400/8a2be2/ffffff&text=TalentEdge",
    "foundedYear": 2011,
    "clientsServed": 1200,
    "languagesSupported": ["English", "Hindi", "Marathi"],
    "featuredServices": ["Recruitment Process Outsourcing", "Payroll & Compliance Advisory", "Performance Management"]
  },
  {
    "id": 14,
    "serviceName": "GreenField Agro Advisory",
    "category": "Consulting",
    "description": "Provides consultancy for modern farming, crop yield optimization, soil analysis, and agricultural technology implementation.",
    "averagePricing": "₹25,000 - ₹1,00,000",
    "rating": 4.6,
    "reviewsCount": 310,
    "location": "Ludhiana, Punjab",
    "availability": "Offline",
    "contact": {"email": "support@greenfieldagro.in", "phone": "+91-8854123678"},
    "website": "https://www.greenfieldagro.in",
    "imageUrl": "https://dummyimage.com/600x400/228b22/ffffff&text=GreenField",
    "foundedYear": 2008,
    "clientsServed": 950,
    "languagesSupported": ["English", "Hindi", "Punjabi"],
    "featuredServices": ["Soil Testing & Advisory", "Precision Farming Solutions", "Organic Farming Consultancy"]
  },
  {
    "id": 15,
    "serviceName": "MediCare Health Services 2",
    "category": "Service",
    "description": "Offers diagnostic tests, preventive health check-ups, telemedicine consultation, and 24/7 ambulance services.",
    "averagePricing": "₹500 - ₹10,000",
    "rating": 4.3,
    "reviewsCount": 1120,
    "location": "Mumbai, Maharashtra",
    "availability": "Both",
    "contact": {"email": "info@medicarehealth.in", "phone": "+91-9123456789"},
    "website": "https://www.medicarehealth.in",
    "imageUrl": "https://dummyimage.com/600x400/dc143c/ffffff&text=MediCare+2",
    "foundedYear": 2015,
    "clientsServed": 15000,
    "languagesSupported": ["English", "Hindi", "Marathi"],
    "featuredServices": ["Home Sample Collection", "Full Body Check-up", "Telemedicine with Specialists"]
  },
  {
    "id": 16,
    "serviceName": "EduMentors Coaching",
    "category": "Consulting",
    "description": "Provides educational consulting for competitive exams, study abroad guidance, and career counselling.",
    "averagePricing": "₹20,000 - ₹1,50,000",
    "rating": 4.7,
    "reviewsCount": 860,
    "location": "Delhi NCR",
    "availability": "Both",
    "contact": {"email": "counsel@edumentors.in", "phone": "+91-9312457890"},
    "website": "https://www.edumentors.in",
    "imageUrl": "https://dummyimage.com/600x400/4682b4/ffffff&text=EduMentors",
    "foundedYear": 2012,
    "clientsServed": 4000,
    "languagesSupported": ["English", "Hindi"],
    "featuredServices": ["Career Counselling", "Overseas Education Guidance", "Competitive Exam Mentorship"]
  },
  {
    "id": 17,
    "serviceName": "SkillUp IT Training",
    "category": "Service",
    "description": "Provides IT training programs for freshers and professionals covering software development and cloud computing.",
    "averagePricing": "₹15,000 - ₹70,000",
    "rating": 4.4,
    "reviewsCount": 1300,
    "location": "Hyderabad, Telangana",
    "availability": "Online",
    "contact": {"email": "training@skillupit.in", "phone": "+91-9845236712"},
    "website": "https://www.skillupit.in",
    "imageUrl": "https://dummyimage.com/600x400/ff8c00/ffffff&text=SkillUp",
    "foundedYear": 2016,
    "clientsServed": 7000,
    "languagesSupported": ["English", "Hindi", "Telugu"],
    "featuredServices": ["Full Stack Development Training", "AWS & Cloud Computing", "Data Analytics with Python"]
  },
  {
    "id": 18,
    "serviceName": "SafeHome Security Services",
    "category": "Service",
    "description": "Offers CCTV surveillance setup, smart home security systems, and guard hiring for residential and commercial properties.",
    "averagePricing": "₹10,000 - ₹1,00,000",
    "rating": 4.5,
    "reviewsCount": 740,
    "location": "Bangalore, Karnataka",
    "availability": "Offline",
    "contact": {"email": "support@safehomesecurity.in", "phone": "+91-9876543102"},
    "website": "https://www.safehomesecurity.in",
    "imageUrl": "https://dummyimage.com/600x400/708090/ffffff&text=SafeHome",
    "foundedYear": 2014,
    "clientsServed": 3200,
    "languagesSupported": ["English", "Hindi", "Kannada"],
    "featuredServices": ["CCTV Camera Installation", "Biometric Security Systems", "24/7 Security Guards"]
  },
  {
    "id": 19,
    "serviceName": "UrbanNest Interior Solutions",
    "category": "Service",
    "description": "Specializes in modern and traditional home interiors, offering customized designs and furniture planning.",
    "averagePricing": "₹2,50,000 - ₹20,00,000",
    "rating": 4.7,
    "reviewsCount": 610,
    "location": "Hyderabad, Telangana",
    "availability": "Both",
    "contact": {"email": "contact@urbannestinteriors.in", "phone": "+91 91234 55678"},
    "website": "https://www.urbannestinteriors.in",
    "imageUrl": "https://dummyimage.com/600x400/d2b48c/000000&text=UrbanNest",
    "foundedYear": 2012,
    "clientsServed": 2700,
    "languagesSupported": ["English", "Hindi", "Telugu"],
    "featuredServices": ["Modular Kitchen Design", "Office Interior Setup", "Space Saving Furniture", "3D Visualization"]
  },
  {
    "id": 20,
    "serviceName": "MediCare Health Consultancy",
    "category": "Consulting",
    "description": "Provides expert consultancy in healthcare operations, hospital management, and medical tourism.",
    "averagePricing": "₹50,000 - ₹5,00,000",
    "rating": 4.6,
    "reviewsCount": 398,
    "location": "Chennai, Tamil Nadu",
    "availability": "Both",
    "contact": {"email": "info@medicareconsultancy.in", "phone": "+91 99440 22334"},
    "website": "https://www.medicareconsultancy.in",
    "imageUrl": "https://dummyimage.com/600x400/4169e1/ffffff&text=MediCare",
    "foundedYear": 2016,
    "clientsServed": 1200,
    "languagesSupported": ["English", "Hindi", "Tamil"],
    "featuredServices": ["Hospital Accreditation Consulting", "Digital Health Solutions", "Medical Tourism Guidance"]
  },
  {
    "id": 21,
    "serviceName": "EcoSmart Waste Management",
    "category": "Service",
    "description": "Delivers sustainable waste management services including e-waste recycling and residential composting solutions.",
    "averagePricing": "₹20,000 - ₹3,00,000",
    "rating": 4.4,
    "reviewsCount": 310,
    "location": "Pune, Maharashtra",
    "availability": "Offline",
    "contact": {"email": "support@ecosmartwaste.in", "phone": "+91 88550 33445"},
    "website": "https://www.ecosmartwaste.in",
    "imageUrl": "https://dummyimage.com/600x400/008080/ffffff&text=EcoSmart",
    "foundedYear": 2013,
    "clientsServed": 1800,
    "languagesSupported": ["English", "Hindi", "Marathi"],
    "featuredServices": ["E-waste Collection", "Corporate Waste Auditing", "Composting Solutions"]
  },
  {
    "id": 22,
    "serviceName": "SkillUp Career Consultancy",
    "category": "Consulting",
    "description": "Provides career counseling, resume building, and skill assessments for freshers and professionals.",
    "averagePricing": "₹2,000 - ₹25,000",
    "rating": 4.5,
    "reviewsCount": 765,
    "location": "Indore, Madhya Pradesh",
    "availability": "Online",
    "contact": {"email": "counsel@skillupcareer.in", "phone": "+91 93022 11234"},
    "website": "https://www.skillupcareer.in",
    "imageUrl": "https://dummyimage.com/600x400/9932cc/ffffff&text=SkillUp",
    "foundedYear": 2019,
    "clientsServed": 5400,
    "languagesSupported": ["English", "Hindi"],
    "featuredServices": ["Career Counseling", "Skill Gap Analysis", "Resume Building", "Placement Assistance"]
  },
  {
    "id": 23,
    "serviceName": "SmartLegal Consultancy",
    "category": "Consulting",
    "description": "Offers corporate law consultancy, contract drafting, and intellectual property rights advisory.",
    "averagePricing": "₹15,000 - ₹1,50,000",
    "rating": 4.8,
    "reviewsCount": 520,
    "location": "New Delhi, Delhi",
    "availability": "Both",
    "contact": {"email": "legal@smartlegal.in", "phone": "+91 98110 77889"},
    "website": "https://www.smartlegal.in",
    "imageUrl": "https://dummyimage.com/600x400/b22222/ffffff&text=SmartLegal",
    "foundedYear": 2011,
    "clientsServed": 3200,
    "languagesSupported": ["English", "Hindi"],
    "featuredServices": ["Contract Drafting", "Company Incorporation", "IPR Filing", "Corporate Compliance Consulting"]
  },
  {
    "id": 24,
    "serviceName": "AgriConnect Solutions",
    "category": "Service",
    "description": "Connects farmers with marketplaces, offering consultancy in agri-tech adoption and supply chain optimization.",
    "averagePricing": "₹5,000 - ₹1,00,000",
    "rating": 4.3,
    "reviewsCount": 280,
    "location": "Nagpur, Maharashtra",
    "availability": "Both",
    "contact": {"email": "help@agriconnect.in", "phone": "+91 98902 77661"},
    "website": "https://www.agriconnect.in",
    "imageUrl": "https://dummyimage.com/600x400/556b2f/ffffff&text=AgriConnect",
    "foundedYear": 2017,
    "clientsServed": 2200,
    "languagesSupported": ["English", "Hindi", "Marathi"],
    "featuredServices": ["Agri Supply Chain Consultancy", "Organic Farming Guidance", "Market Linkage", "Agri-Tech Training"]
  },
  {
    "id": 25,
    "serviceName": "Eventura Wedding & Events",
    "category": "Service",
    "description": "Provides full-scale event management and wedding planning services, including theme design and logistics.",
    "averagePricing": "₹5,00,000 - ₹50,00,000",
    "rating": 4.9,
    "reviewsCount": 890,
    "location": "Jaipur, Rajasthan",
    "availability": "Offline",
    "contact": {"email": "info@eventuraevents.in", "phone": "+91 98290 33456"},
    "website": "https://www.eventuraevents.in",
    "imageUrl": "https://dummyimage.com/600x400/da70d6/000000&text=Eventura",
    "foundedYear": 2009,
    "clientsServed": 4500,
    "languagesSupported": ["English", "Hindi", "Rajasthani"],
    "featuredServices": ["Destination Weddings", "Corporate Events", "Birthday Parties", "Stage & Theme Decor"]
  }
];


/**
 * Fetches all service and consultancy data.
 * In a real application, this would be an async API call.
 * @returns {Promise<Array>} A promise that resolves to the full list of services.
 */
export const fetchData = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(allData);
    }, 500); // Simulate network delay
  });
};

/**
 * Fetches a single item by its ID.
 * @param {string|number} id - The ID of the item to fetch.
 * @returns {Promise<Object|null>} A promise that resolves to the found item or null.
 */
export const fetchItemById = (id) => {
    return new Promise((resolve) => {
        setTimeout(() => {
            const item = allData.find(d => d.id.toString() === id.toString());
            resolve(item || null);
        }, 300); // Simulate network delay
    });
};